
SYS = {
    0x004: ('VMGetIoManager', 'VmIoManagerTag'),
    0x00c: ('VMGetLcdManager', 'VmLcdManagerTag'),
    0x014: ('VMGetTimeManager', 'VmTimeManagerTag'),
    0x01c: ('VMGetCtrlManager', 'VmCtrlManagerTag'),
    0x024: ('VMGetMemoryManager', 'VmMemoryManagerTag'),
    0x02c: ('VMGetBillingManager', 'VmBillingManagerTag'),
    0x034: ('VMGetScreenManager', 'VmScreenManagerTag'),
    0x03c: ('VMGetNetManager', 'VmNetManagerTag'),
    0x044: ('VMGetUcs2StrManager', 'VmUcs2StrManagerTag'),
    0x04c: ('VMGetSysManager', 'VmSysManagerTag'),
    0x054: ('VMGetDFScriptManager', 'VmDFScriptManagerTag'),
    0x05c: ('VMGetGameLcdManager', 'VmGameLcdManagerTag'),
    0x064: ('VMGetGameUtilManager', 'VmGameUtilManagerTag'),
    0x06c: ('VMGetDFEnginelManager', 'VmDFEnginelManagerTag'),
    0x074: ('VMGetNetAppManager', 'VmNetAppManagerTag'),
    0x07c: ('VMGetAudioManager', 'VmAudioManagerTag'),
    0x084: ('VMGetGameManagerOld', 'GameManagerOldTag'),
    0x090: ('vMGetGSensorManager', None),
    0x098: ('vMGetVmStdManager', 'VmStdManagerTag'),
    0x0a0: ('vMGetDlLoadManager', 'VmDlLoadManagerTag'),
    0x0a4: ('vMGetDlRsManager', 'VmDlResourceManagerTag'),
    0x0ac: ('vMGetDlImageManager', 'VmDlImageManagerTag'),
    0x0b8: ('vMGetVmImManager', 'VmImManagerTag'),
    0x0c8: ('VmGetVideoManager', 'VmVideoManagerTag'),
    0x0cc: ('VmGetDlWPayManager', 'VmDLWPayManagerTag'),
}

SIZE = {
    'GameManagerOldTag': 636,
    'VmAudioManagerTag': 124,
    'VmBillingManagerTag': 176,
    'VmCtrlManagerTag': 84,
    'VmDFEnginelManagerTag': 60,
    'VmDFScriptManagerTag': 88,
    'VmDLWPayManagerTag': 36,
    'VmDlAppStoreManagerTag': 156,
    'VmDlImageManagerTag': 56,
    'VmDlLoadManagerTag': 44,
    'VmDlResourceManagerTag': 80,
    'VmGSensorManagerrTag': 48,
    'VmGameLcdManagerTag': 160,
    'VmGameUtilManagerTag': 160,
    'VmImManagerTag': 32,
    'VmIoManagerTag': 120,
    'VmLcdManagerTag': 380,
    'VmManagerTag': 212,
    'VmMemoryManagerTag': 108,
    'VmNetAppManagerTag': 244,
    'VmNetManagerTag': 172,
    'VmScreenManagerTag': 48,
    'VmStdManagerTag': 88,
    'VmSysManagerTag': 460,
    'VmTimeManagerTag': 40,
    'VmUcs2StrManagerTag': 44,
    'VmVideoManagerTag': 152,
}

MGR = {
    'GameManagerOldTag': {
        0x000: ('IMG_CreateImageFormRes', ''),
        0x004: ('DrawImageWithClip', ''),
        0x008: ('DrawImageClipAndAlpha', ''),
        0x00c: ('DrawFullScreen', ''),
        0x010: ('DrawNumber', ''),
        0x014: ('DrawUI', ''),
        0x018: ('DrawUIFourXRepeat', ''),
        0x01c: ('DrawUISingleRepeat', ''),
        0x020: ('DrawUIHorizontal', ''),
        0x024: ('DrawString', ''),
        0x028: ('IMG_Destory', ''),
        0x02c: ('GAME_isKeyDown', ''),
        0x030: ('GAME_isKeyHold', ''),
        0x038: ('SetClip', ''),
        0x03c: ('IMG_GetHeight', ''),
        0x040: ('IMG_GetWidth', ''),
        0x044: ('ToRGB', ''),
        0x048: ('DrawVLine', ''),
        0x04c: ('DrawHLine', ''),
        0x050: ('DrawLine', ''),
        0x054: ('DrawRect', ''),
        0x058: ('FillRect', ''),
        0x05c: ('GetStreamDataFormRes', ''),
        0x060: ('GetClip', ''),
        0x064: ('OldLib_064', ''),
        0x068: ('CheckClip', ''),
        0x06c: ('DrawLineEx', ''),
        0x070: ('GetFontWidth', ''),
        0x074: ('GetFontWidth_char', ''),
        0x078: ('GetFontHeight', ''),
        0x07c: ('GetFontHeight_char', ''),
        0x080: ('DrawImageWithClipEx', ''),
        0x084: ('DrawImageClipAndAlphaEx', ''),
        0x088: ('DrawImageNumberEx', ''),
        0x08c: ('OldLib_08c', ''),
        0x090: ('DrawStringEx', ''),
        0x094: ('OldLib_094', ''),
        0x098: ('OldLib_098', ''),
        0x09c: ('OldLib_09c', ''),
        0x0a0: ('OldLib_0a0', ''),
        0x0a4: ('OldLib_0a4', ''),
        0x0a8: ('OldLib_0a8', ''),
        0x0ac: ('OldLib_0ac', ''),
        0x0b0: ('OldLib_0b0', ''),
        0x0b4: ('OldLib_0b4', ''),
        0x0b8: ('RefresScreen', ''),
        0x0bc: ('NumToZhiFei', ''),
        0x0c0: ('GetLCDBuffer', ''),
        0x0c4: ('CdRect', ''),
        0x0c8: ('CdRectPoint', ''),
        0x0cc: ('CdRect2', ''),
        0x0d0: ('CdRectPoint2', ''),
        0x0d4: ('Abs', ''),
        0x0d8: ('Max', ''),
        0x0dc: ('Min', ''),
        0x0e0: ('Random', ''),
        0x0e4: ('Sqrt', ''),
        0x0e8: ('initMemoryBlock', ''),
        0x0ec: ('InitSprite', ''),
        0x0f0: ('SCREEN_ChangeScreen', ''),
        0x0f4: ('SCREEN_NotifyLoadResource', ''),
        0x0f8: ('SCREEN_IsPointerHold', ''),
        0x0fc: ('SCREEN_IsPointerDown', ''),
        0x100: ('SCREEN_IsPointerUp', ''),
        0x104: ('SCREEN_IsPointerDrag', ''),
        0x108: ('SCREEN_GetPointerX', ''),
        0x10c: ('SCREEN_GetPointerY', ''),
        0x110: ('Get_CurKeyDownState', ''),
        0x11c: ('InitTextBox', ''),
        0x120: ('initDFMap', ''),
        0x124: ('initDFMapRenderBuffer', ''),
        0x128: ('initDFMapVScollBuffer', ''),
        0x12c: ('initDFPictureLibrary', ''),
        0x130: ('initDFRecord', ''),
        0x134: ('initDFScene', ''),
        0x138: ('initDFSpriteLibrary', ''),
        0x13c: ('initDFWindows', ''),
        0x140: ('initDreamFactoryEngine', ''),
        0x144: ('DF_SetDataPackage', ''),
        0x148: ('DF_GetDataPackage', ''),
        0x14c: ('DF_GetResourceByResourceID', ''),
        0x150: ('DF_GetResourceByFileName', ''),
        0x154: ('DF_GetResourceNameByID', ''),
        0x158: ('DF_GetResourceIDByFileName', ''),
        0x15c: ('DF_GetTResource', ''),
        0x160: ('DF_GetStreamTResource', ''),
        0x164: ('DF_DataPackage_ShowFileList', ''),
        0x168: ('DF_String_Equal', ''),
        0x16c: ('DF_ReadShort', ''),
        0x170: ('DF_ReadInt', ''),
        0x174: ('DF_File_ReadShort', ''),
        0x178: ('DF_File_ReadInt', ''),
        0x17c: ('DF_WriteShort', ''),
        0x180: ('DF_WriteInt', ''),
        0x184: ('DF_ReadString', ''),
        0x188: ('DF_ReadStringEx', ''),
        0x18c: ('DF_File_ReadString', ''),
        0x190: ('DF_File_ReadToBuffer', ''),
        0x194: ('DF_ReadString2', ''),
        0x198: ('DF_GetMemoryBlock', ''),
        0x19c: ('DF_Sin', ''),
        0x1a0: ('DF_Cos', ''),
        0x1a4: ('DF_Degree', ''),
        0x1a8: ('DF_CollectionTest', ''),
        0x1ac: ('DF_SwapVal', ''),
        0x1b0: ('DF_GetFormatString', ''),
        0x1b4: ('initDFActor', ''),
        0x1b8: ('initDFDataPackage', ''),
        0x1bc: ('XS_Init', ''),
        0x1c0: ('XS_ShutDown', ''),
        0x1c4: ('XS_LoadScript', ''),
        0x1c8: ('XS_RunScripts', ''),
        0x1cc: ('XS_ResetScript', ''),
        0x1d0: ('XS_CallScriptFunc', ''),
        0x1d4: ('XS_InvokeScriptFunc', ''),
        0x1d8: ('XS_RegisterHostAPIFunc', ''),
        0x1dc: ('XS_StartScript', ''),
        0x1e0: ('XS_StopScript', ''),
        0x1e4: ('XS_PauseScript', ''),
        0x1e8: ('XS_UnpauseScript', ''),
        0x1ec: ('XS_GetReturnValueAsInt', ''),
        0x1f0: ('XS_GetReturnValueAsFloat', ''),
        0x1f4: ('XS_GetReturnValueAsString', ''),
        0x1f8: ('XS_ReturnFromHost', ''),
        0x1fc: ('XS_ReturnIntFromHost', ''),
        0x200: ('XS_ReturnFloatFromHost', ''),
        0x204: ('XS_ReturnStringFromHost', ''),
        0x208: ('XS_GetParamAsInt', ''),
        0x20c: ('XS_GetParamAsFloat', ''),
        0x210: ('XS_GetParamAsString', ''),
        0x214: ('memcpy', ''),
        0x218: ('strlen', ''),
        0x21c: ('memset', ''),
        0x220: ('sprintf', ''),
        0x224: ('vm_log_trace', ''),
        0x228: ('VmGetRand', ''),
        0x22c: ('vsprintf', ''),
        0x230: ('strncpy', ''),
        0x234: ('strcpy', ''),
        0x238: ('strcat', ''),
        0x23c: ('atol', ''),
        0x240: ('memmove', ''),
        0x244: ('atoi', ''),
        0x248: ('BILLING_GetPayNumByAppId', ''),
        0x24c: ('BILLING_GetRemainDay', ''),
        0x250: ('BILLING_Pay', ''),
        0x254: ('BILLING_PayMoreTimes', ''),
        0x258: ('BILLING_IsRegisterBillingInfo', ''),
        0x25c: ('BILLING_RegisterBillingInfo', ''),
        0x260: ('BILLING_SetBillingStatus', ''),
        0x264: ('BILLING_GetBillingStatus', ''),
        0x268: ('BILLING_IsNeedPay', ''),
        0x26c: ('BILLING_IsInTryStatus', ''),
        0x270: ('Game_OpenBillingPromptWin', ''),
        0x274: ('vMstricmp', ''),
    },
    'VmAudioManagerTag': {
        0x000: ('vMAudioSetVolume', 'void (VMUINT8, VMBOOLEAN)'),
        0x004: ('vMAudioPlayByData', 'VMINT16 (VMUINT8 *, VMUINT8)'),
        0x008: ('vMAudioPlayWithDataPackage', 'VMINT16 (gm_u32, VMUINT8, DF_DataPackage *)'),
        0x00c: ('vMAudioPlayForGame', 'VMINT16 (gm_u32, VMUINT8)'),
        0x010: ('vMAudioPlayForApp', 'VMINT16 (gm_u32, VMUINT8)'),
        0x014: ('vMAudioPause', 'VMBOOLEAN ()'),
        0x018: ('vMAudioResume', 'VMBOOLEAN ()'),
        0x01c: ('vMAudioStop', 'VMBOOLEAN ()'),
        0x020: ('vMAduioGetState', 'VMUINT8 ()'),
        0x024: ('VmMp3PlayByStream', 'VMBOOLEAN (vm_mp3PlayCallback)'),
        0x028: ('VmMp3PauseByStream', 'void ()'),
        0x02c: ('VmMp3ResumeByStream', 'void ()'),
        0x030: ('VmMp3StopBystream', 'void ()'),
        0x034: ('VmMp3PlayByFile', 'void (VMUINT16 *, vm_mp3PlayCallback)'),
        0x038: ('VmMp3PauseByFile', 'void ()'),
        0x03c: ('VmMp3ResumeByFile', 'void ()'),
        0x040: ('VmMp3StopByFile', 'void ()'),
        0x044: ('VmMp3GetProgressTime', 'void (VMUINT32 *, VMUINT32 *)'),
        0x048: ('VmMp3StreamInit', 'void (vm_mp3GetByteFromBuffer_CallBack, vm_mp3PeekBuffer_CallBack, vm_mp3setBufferPos_CallBack)'),
        0x04c: ('VmAMRStartPlayInit', 'void ('),
        0x050: ('VmAMRStopPlay', 'void ()'),
        0x054: ('VmAMRplay', 'void (VMUINT16 *, VMUINT16)'),
        0x058: ('VmAMRStartRecord', 'VMBOOLEAN (void *)'),
        0x05c: ('VmAMRStopRecord', 'void ()'),
        0x060: ('VmSetAMRRecBS', 'void (VMUINT32)'),
        0x064: ('VmMp3PlayByFileEx', 'void (VmFileDevType, VMUINT16 *, vm_mp3PlayCallback)'),
        0x068: ('vMStartAudioRecordEx', 'VMBOOLEAN (CB_AMR_DECODER *, CBAudioFormat)'),
        0x06c: ('vMStopAudioRecordEx', 'void ()'),
        0x070: ('CB_AUD_StartPlay_InitEx', 'void (CB_AMR_DECODER *, CBAudioFormat)'),
        0x074: ('CB_AUD_StartPlayEx', 'void (VMUINT16 *, VMUINT16, CBAudioFormat)'),
        0x078: ('CB_AUD_StopPlayEx', 'void ()'),
    },
    'VmBillingManagerTag': {
        0x000: ('BILLING_GetPayNumByAppId', 'VMUINT16 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)'),
        0x004: ('BILLING_GetRemainDay', 'VMUINT32 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)'),
        0x008: ('BILLING_Pay', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t)'),
        0x00c: ('BILLING_PayMoreTimes', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT16)'),
        0x010: ('BILLING_IsRegisterBillingInfo', 'VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)'),
        0x014: ('BILLING_RegisterBillingInfo', 'VMBOOLEAN (NETAPP_BILLING_APPID_TYPE, VMUINT32)'),
        0x018: ('BILLING_SetBillingStatus', 'VMBOOLEAN (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_STATUS_TYPE)'),
        0x01c: ('BILLING_GetBillingStatus', 'NETAPP_BILLING_STATUS_TYPE (NETAPP_BILLING_APPID_TYPE)'),
        0x020: ('BILLING_IsNeedPay', 'VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)'),
        0x024: ('BILLING_IsInTryStatus', 'VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)'),
        0x028: ('BIllING_OpenBillingPromptWin', 'void (NETAPP_BILLING_APPID_TYPE)'),
        0x02c: ('BILLING_GetTryDay', 'VMUINT16 (NETAPP_BILLING_APPID_TYPE)'),
        0x030: ('BILLING_PayForCBB', 'void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t)'),
        0x034: ('BILLING_PayForPwd', 'void (Billing_callback_func_t)'),
        0x038: ('BILLING_GetCdownOption5', 'VMUINT8 ()'),
        0x03c: ('Billing_SendSpecSms', 'VMBOOLEAN (VMUINT16, VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN, SmSCallback)'),
        0x040: ('Billing_CancelSms', 'VMBOOLEAN ()'),
        0x044: ('CDownIsMonthApp', 'VMBOOLEAN (VMUINT16, NETAPP_BILLING_METHOD_TYPE)'),
        0x048: ('CDownGetFileNameByAppID', 'VMBOOLEAN (VMUINT16, VMUINT8 **, VMUINT8 *, VMUINT16 *)'),
        0x04c: ('BILLING_GetSmsNum', 'VMUINT16 (VMUINT16, VMUINT8)'),
        0x050: ('BILLING_NewMonthPay', 'VMBOOLEAN ('),
        0x054: ('BILLING_NewMonthCancel', 'VMBOOLEAN (NewMonthPayInfo *, Billing_callback_func_t)'),
        0x058: ('BILLING_CleanAppMonthBillInfo', 'VMBOOLEAN (VMUINT16)'),
        0x05c: ('BILLING_GetValidDayByAppId', 'VMUINT16 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)'),
        0x060: ('BILLING_GetBillSmsAddr', 'void (VMUINT16, VMUINT16, VMCHAR *)'),
        0x064: ('BILLING_GetBillSmsSuf', 'void (VMUINT16, VMUINT16, VMCHAR *)'),
        0x068: ('BILLING_Pay2', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32)'),
        0x06c: ('BILLING_GetAppUsedStatus', 'VMUINT8 (VMUINT16)'),
        0x070: ('BILLING_SetAppUsedStatus', 'void (VMUINT16, VMUINT8)'),
        0x074: ('BILLING_GetPayTipContent', 'void (VMUINT16, VMUINT16, VMCHAR *)'),
        0x078: ('BILLING_Pay3', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32, VMBOOLEAN)'),
        0x07c: ('BILLING_SendRegisterSms', 'VMBOOLEAN (VMCHAR *, VMCHAR *, VMBOOLEAN, Billing_callback_func_t)'),
        0x080: ('BILLING_CDownOption8', 'VMUINT8 ()'),
        0x084: ('BILLING_CDownOption9', 'VMUINT8 ()'),
        0x088: ('BILLING_CDownOption10', 'VMUINT8 ()'),
        0x08c: ('BILLING_Register', 'void (SmSCallback)'),
        0x090: ('BILLING_PayForCBB3', 'void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t, VMBOOLEAN)'),
        0x094: ('BILLING_IsWPay', 'VMBOOLEAN ()'),
        0x098: ('BILLING_GetPayType', 'VMUINT8 (VMUINT16, VMUINT16)'),
        0x09c: ('BILLING_GetDownLoadFee', 'VMUINT8 (VMUINT16)'),
        0x0a0: ('BILLING_GETUsedFee', 'VMUINT8 (VMUINT16)'),
        0x0a4: ('BILLING_Pay3InMM', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32, VMBOOLEAN)'),
        0x0a8: ('BILLING_PayForCBB3InMM', 'void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t, VMBOOLEAN, VMUINT16, VMCHAR *)'),
        0x0ac: ('BILLING_GetFMMPayTip', 'void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, VMUINT16, VMCHAR *, Billing_callback_func_t)'),
    },
    'VmCtrlManagerTag': {
        0x000: ('VmPubDrawSoftkeyBar', 'void (VmImageType *, VMSTR, VMSTR, VMSTR)'),
        0x004: ('VmPubDrawSoftkeyBarEx', 'void (VmImageType *, VMSTR, VMSTR, VMSTR, VMUINT16)'),
        0x008: ('VmPubDrawWinTitle', 'void (VmImageType *, VMSTR)'),
        0x00c: ('vmPubDrawWinTitleEx', 'void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x010: ('vmPubTpPressSoftkeyBar', 'VMBOOLEAN (VmImageType *, VMSTR, VMINT16, VMINT16, VmSoftType)'),
        0x014: ('InitCoolbarListBox', 'VMBOOLEAN ('),
        0x018: ('InitCoolbarListBoxEx', 'VMBOOLEAN (CoolbarListBox **, VMUINT16, Rect, VMUINT8, VMBOOLEAN, CoolbarListBox_callback_func_t)'),
        0x01c: ('CbPopBox_Init', 'void ('),
        0x020: ('CbPopBox_InitEx', 'void (CB_PopBox **'),
        0x024: ('VmPubDrawWinTitleWithColor', 'void (VmImageType *, VMSTR, VMUINT16)'),
        0x028: ('vmInputText', 'VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)'),
        0x02c: ('vmInputPassword', 'VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)'),
        0x030: ('vmInputClose', 'void ()'),
        0x034: ('vmInputIsOpen', 'VMBOOLEAN ()'),
        0x038: ('vmInputDummy', 'void (void *)'),
        0x03c: ('vmPubDrawUcs2SoftkeyBar', 'void (VmImageType *, VMWSTR, VMWSTR, VMWSTR)'),
        0x040: ('vmPubDrawUcs2SoftkeyBarEx', 'void (VmImageType *, VMWSTR, VMWSTR, VMWSTR, VMUINT16)'),
        0x044: ('vmPubTpPressUcs2SoftkeyBar', 'VMBOOLEAN (VmImageType *, VMWSTR, VMINT16, VMINT16, VmSoftType)'),
        0x048: ('vmPubDrawUcs2WinTitle', 'void (VmImageType *, VMWSTR)'),
        0x04c: ('vmPubDrawUcs2WinTitleWithColor', 'void (VmImageType *, VMWSTR, VMUINT16)'),
        0x050: ('vmPubDrawUcs2WinTitleEx', 'void (VmImageType *, VMWSTR, VMUINT16, VMUINT16, VMUINT16)'),
    },
    'VmDFEnginelManagerTag': {
        0x000: ('initDFMap', 'void ('),
        0x004: ('initDFMapRenderBuffer', 'void ('),
        0x008: ('initDFMapVScollBuffer', 'void ('),
        0x00c: ('initDFPictureLibrary', 'void (DF_PictureLibrary *, int)'),
        0x010: ('initDFRecord', 'void ('),
        0x014: ('initDFScene', 'void ('),
        0x018: ('initDFSpriteLibrary', 'void ('),
        0x01c: ('initDFWindows', 'void ('),
        0x020: ('initDreamFactoryEngine', 'void ()'),
        0x024: ('initDFActor', 'void ('),
        0x028: ('initDFDataPackage', 'void (DF_DataPackage *, gm_s16)'),
        0x02c: ('GetSceneMapVScollBufferPtr', 'DF_MapVScollBuffer *()'),
        0x030: ('GetDF_MapRenderBufferPtr', 'DF_MapRenderBuffer *()'),
        0x034: ('DF_MapRenderBuffer_Windows_Render', 'void (void *)'),
        0x038: ('DF_SendMessage', 'void (DF_Windows *, short, void *)'),
    },
    'VmDFScriptManagerTag': {
        0x000: ('XS_Init', 'Script *()'),
        0x004: ('XS_ShutDown', 'void ()'),
        0x008: ('XS_LoadScript', 'int (char *'),
        0x00c: ('XS_RunScripts', 'void (int)'),
        0x010: ('XS_ResetScript', 'void (int)'),
        0x014: ('XS_CallScriptFunc', 'void (int, char *)'),
        0x018: ('XS_InvokeScriptFunc', 'void (int, char *)'),
        0x01c: ('XS_RegisterHostAPIFunc', 'void (int, char *, HostAPIFuncPntr)'),
        0x020: ('XS_StartScript', 'void (int)'),
        0x024: ('XS_StopScript', 'void (int)'),
        0x028: ('XS_PauseScript', 'void (int, int)'),
        0x02c: ('XS_UnpauseScript', 'void (int)'),
        0x030: ('XS_GetReturnValueAsInt', 'int (int)'),
        0x034: ('XS_GetReturnValueAsFloat', 'float (int)'),
        0x038: ('XS_GetReturnValueAsString', 'char *(int)'),
        0x03c: ('XS_ReturnFromHost', 'void (int, int)'),
        0x040: ('XS_ReturnIntFromHost', 'void (int, int, int)'),
        0x044: ('XS_ReturnFloatFromHost', 'void (int, int, float)'),
        0x048: ('XS_ReturnStringFromHost', 'void (int, int, char *)'),
        0x04c: ('XS_GetParamAsInt', 'int (int, int)'),
        0x050: ('XS_GetParamAsFloat', 'float (int, int)'),
        0x054: ('XS_GetParamAsString', 'char *(int, int)'),
    },
    'VmDLWPayManagerTag': {
        0x000: ('vmWPayEnterCharge', 'void (VMBOOLEAN, WPayEnterCallBack, VMUINT16, VMUINT32)'),
        0x004: ('vmWPayEnterBuy', 'void (VMBOOLEAN, VMUINT32, WPayEnterCallBack, VMUINT16'),
        0x008: ('vmWPayGetCbMoney', 'void (VMBOOLEAN, WPayEnterCallBack)'),
        0x00c: ('vmWPaySetPayName', 'void (VMCHAR *)'),
        0x010: ('vmWPaySetPayPassword', 'void (VMCHAR *)'),
        0x014: ('vmWPaySetPayPhone', 'void (VMCHAR *)'),
        0x018: ('vmWPaySetPayPhonePassword', 'void (VMCHAR *)'),
        0x01c: ('vmGetIMEI', 'void (VMSTR, VMUINT32)'),
        0x020: ('vmWPayEnterPay', 'void (VMBOOLEAN, void *)'),
    },
    'VmDlAppStoreManagerTag': {
        0x000: ('vmAppStoreInstall', 'VMBOOLEAN ('),
        0x004: ('vmAppStoreInstallEx', 'VMBOOLEAN (AppDataType *, AppStoreCallback)'),
        0x008: ('vmAppStoreUninstall', 'VMBOOLEAN (VMUINT32, AppType_e)'),
        0x00c: ('vmAppStoreUninstallEx', 'VMBOOLEAN (VMUINT32 *, AppType_e, VMUINT16)'),
        0x010: ('vmAppStoreGetAppInfo', 'VMBOOLEAN ('),
        0x014: ('vmAppStoreGetInstalledAppInfos', 'void ('),
        0x018: ('vmAppStoreReleaseAppInfos', 'void (AppInfoType **)'),
        0x01c: ('vmAppStorePushMsg', 'void (VMUINT32, VMCHAR *)'),
        0x020: ('vmAppStoreRunJavaAp', 'VMBOOLEAN (VMUINT32)'),
        0x024: ('vmAppStoreRunJavaApEx', 'VMBOOLEAN (VMUINT32, AppStoreCallback)'),
        0x028: ('vmAppStoreRunCbeAp', 'VMBOOLEAN (VMUINT32)'),
        0x02c: ('vmAppStoreSupportJava', 'VMBOOLEAN ()'),
        0x030: ('vmAppStoreGetPath', 'VMUINT16 *()'),
        0x034: ('vmGetPhoneType', 'PhoneType_e ()'),
        0x038: ('vmGetAppNumByType', 'VMBOOLEAN (AppType_e, VMUINT16 *)'),
        0x03c: ('vmGetPhoneSupportApType', 'VMUINT32 ()'),
        0x040: ('vmAppGetHasLocalIcon', 'VMBOOLEAN (VMUINT32, AppType_e)'),
        0x044: ('vmAppRunApByIdAndName', 'VMBOOLEAN (VMUINT32, AppType_e, VMUINT16 *, AppStoreCallback, ApStartSource)'),
        0x048: ('vmAppAddShortCutMenu', 'VMBOOLEAN (AppDataType *, VMUINT16)'),
        0x04c: ('vmAppDelShortCutMenu', 'VMBOOLEAN (AppDataType *, VMUINT16)'),
        0x050: ('vmAppDownLoadAppFile', 'VMBOOLEAN (VMUINT16 *, char *, VMUINT32, DownLoadStateCallBackType)'),
        0x054: ('vmGetAppDownUrl', 'void (char *, VMUINT8, VMUINT32, VMUINT8, VMUINT8, VMCHAR *)'),
        0x058: ('vmAppPreLoadCbeByNameAndId', 'VMUINT8 (VMUINT32, VMUINT16 *)'),
        0x05c: ('vmParseDownloadAppFile', 'VMBOOLEAN (VMUINT16 *, AppDataType *)'),
        0x060: ('vmApsStopDownloadFile', 'VMBOOLEAN ()'),
        0x064: ('vmAppQueryStcExist', 'VMBOOLEAN (AppInfoType *)'),
        0x068: ('vmPreCheckInstallAppPlace', 'SpaceStatus ()'),
        0x06c: ('vmGetInstallFileSystem', 'VmFileDevType ()'),
        0x070: ('vmSetInstallFileSystem', 'void (VmFileDevType)'),
        0x074: ('vmSetRunAppFileSystem', 'void (VmFileDevType)'),
        0x078: ('vmGetRunAppFileSystem', 'VmFileDevType ()'),
        0x07c: ('vmAutoSelectAppDownPlace', 'VMBOOLEAN ()'),
        0x080: ('vmGetApsVerNum', 'VMUINT8 ()'),
        0x084: ('vmReadAppStoreCbeVersion', 'VMBOOLEAN (void *, VMUINT16)'),
        0x088: ('vmWriteAppStoreCbeVersion', 'VMBOOLEAN (const void *, VMUINT16)'),
        0x08c: ('vmGetSecurityCode', 'VMBOOLEAN (VMSTR, VMUINT16)'),
        0x090: ('vmGetSecurityCodeEx', 'VMBOOLEAN (VMSTR, VMUINT16)'),
        0x094: ('vmSetAppStoreName', 'void (VMWSTR)'),
        0x098: ('vmGetAppStoreName', 'VMWSTR ()'),
    },
    'VmDlImageManagerTag': {
        0x000: ('vMDrawStandardImage', 'void (VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)'),
        0x004: ('vMGetStandardImageDimension', 'void (VMUINT8 *, VMUINT32, VMUINT8, VMINT32 *, VMINT32 *)'),
        0x008: ('vMGetStandardImageType', 'void (VMUINT8 *, VMUINT8 *)'),
        0x00c: ('vMDrawStandardImageEx', 'void (VmImageType *, VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)'),
        0x010: ('vMImageDecoderAllocMemory', 'void (VMUINT32, void **)'),
        0x014: ('vMImageDecoderFreeMemory', 'void (void **)'),
        0x018: ('vMImageDecoderGetImageData', 'VMUINT8 *(GddiImage *)'),
        0x01c: ('vMImageDecoderRegImageCodecHandler', 'void (GddiImageFormat'),
        0x020: ('decodePngStartExt', 'VmImageType *(gm_u8 *, VmImageType *, gm_bool)'),
        0x024: ('pngcrc32', 'unsigned int (unsigned int'),
        0x028: ('pnginflate', 'int (void *, int)'),
        0x02c: ('pnginflateInit', 'int (void *)'),
        0x030: ('pnginflateEnd', 'int (void *)'),
        0x034: ('pnginflateReset', 'int (void *)'),
    },
    'VmDlLoadManagerTag': {
        0x000: ('vlDlSetCurrContextAddress', 'void (VMUINT32 **, VMBOOLEAN)'),
        0x004: ('vlDlSetContextAddress', 'void (VMUINT16, VMUINT32 **, VMBOOLEAN)'),
        0x008: ('vlDlUnLoadCurrApp', 'void (VMBOOLEAN)'),
        0x00c: ('vlDlUnLoadApp', 'void (VMUINT16, VMBOOLEAN)'),
        0x010: ('vmDlParseAndCopy', 'VMINT8 (const VMUINT16 *, VMUINT16 *, VMUINT8 *, VMUINT32 *)'),
        0x014: ('vlDlLoadApp', 'VMBOOLEAN (VMUINT16)'),
        0x018: ('vlDlLoadAppEx', 'VMBOOLEAN (VMUINT16, VMUINT8)'),
        0x01c: ('vlDlAppIsInDl', 'VMBOOLEAN (VMUINT16)'),
        0x020: ('vmGetcurrInnerAppId', 'VMUINT16 ()'),
        0x024: ('CBInnerInit_qqIn', 'void (VMUINT8 *, VMUINT32, VMUINT32, VMUINT8 *, VMUINT8 *, VMUINT32, VMUINT32, VMUINT8 *)'),
        0x028: ('VmGetCBEInfoByFileName', 'VMBOOLEAN (VMUINT16 *, VMUINT32 *, VMUINT32 *, VMUINT16 *, VMUINT16 *)'),
    },
    'VmDlResourceManagerTag': {
        0x000: ('vmGetDataPackage', 'DF_DataPackage *(VMBOOLEAN)'),
        0x004: ('vmResGetTxtWithDataPackage', 'VMCHAR *(VMUINT32, DF_DataPackage *)'),
        0x008: ('vmResGetDefTxt', 'VMCHAR *(VMUINT32)'),
        0x00c: ('vmResGetTxtForGame', 'VMCHAR *(VMUINT32)'),
        0x010: ('IMG_InitDataPage', 'void (tResource, gm_s16)'),
        0x014: ('IMG_InitInnerDataPageEx', 'void (tResource)'),
        0x018: ('IMG_InitDataPageEx', 'void (tResource, gm_s16, DF_DataPackage *)'),
        0x01c: ('IMG_InitDataPageTxt', 'void (gm_u32)'),
        0x020: ('IMG_ReleaseDataPage', 'void ()'),
        0x024: ('IMG_CreateImageFormIdEx', 'VmImageType *(gm_u32, DF_DataPackage *, VmImageType *)'),
        0x028: ('IMG_CreateImageFormStream', 'VmImageType *(gm_u8 *, VmImageType *)'),
        0x02c: ('IMG_CreateImageFormName', 'VmImageType *(char *, DF_DataPackage *, VmImageType *)'),
        0x030: ('vMDestoryImage', 'VMBOOLEAN (VmImageType *)'),
        0x034: ('vMCreateImage', 'VMBOOLEAN (VMUINT16, VmImageType *)'),
        0x038: ('vMSetCurrDataPackage', 'void (DF_DataPackage *)'),
        0x03c: ('vMGetCurrDataPackage', 'DF_DataPackage *()'),
        0x040: ('vmFreeDataBuffer', 'void ()'),
        0x044: ('DF_DataPackage_GetFileOffset', 'gm_u32 ()'),
        0x048: ('DF_DataPackage_GetFullPaths', 'gm_u16 *()'),
        0x04c: ('DF_DataPackage_GetFileLens', 'gm_u32 ()'),
    },
    'VmGSensorManagerrTag': {
        0x000: ('vmGsensorInit', 'void ()'),
        0x004: ('vmGsensorStop', 'void ()'),
        0x008: ('vmGsensorStartTile', 'void (VmGSensorBack)'),
        0x00c: ('vmGsensorStartShake', 'void (VmGSensorBack)'),
        0x010: ('vmGsensorStartTurn', 'void (VmGSensorBack)'),
        0x014: ('vmGsensorStartSwing', 'void (VmGSensorBack)'),
        0x018: ('vmGsensorPowerOff', 'void ()'),
        0x01c: ('vmGSenserIsSupportInCb', 'VMBOOLEAN ()'),
        0x020: ('vmGsensorGetDevInfo', 'VMBOOLEAN ('),
        0x024: ('vmGsensorRegistMotionChange', 'VMBOOLEAN (VMUINT32, VMBOOLEAN, GsensorMotionListenrCb, VMBOOLEAN, void *)'),
        0x028: ('vmGsensorRegistNotifyChange', 'VMBOOLEAN (GSENSOR_NOTIFY_PROFILE, VMBOOLEAN, GsensorNotifyCb, VMBOOLEAN, void *)'),
        0x02c: ('vmGsensorGetLastMotionInfo', 'VMBOOLEAN (VMUINT32, VMUINT32 *)'),
    },
    'VmGameLcdManagerTag': {
        0x000: ('CreateImage', 'VmImageType *(tResource)'),
        0x004: ('DrawImageWithClip', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x008: ('DrawImageClipAndAlpha', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x00c: ('DrawFullScreen', 'void (VmImageType *)'),
        0x010: ('DrawNumber', 'void (VmImageType *, gm_s32, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_u8)'),
        0x014: ('DrawUI', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x018: ('DrawUIFourXRepeat', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x01c: ('DrawUISingleRepeat', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x020: ('DrawUIHorizontal', 'void (VmImageType *, gm_s16, gm_s16, gm_s16)'),
        0x024: ('DrawString', 'void (char *, gm_s16, gm_s16, gm_s16, gm_u32)'),
        0x028: ('DrawStringEx', 'void (VmImageType *, char *, gm_s16, gm_s16, gm_s16, gm_u32)'),
        0x02c: ('ReleaseImage', 'void (VmImageType *)'),
        0x030: ('SetClip', 'void (gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x034: ('IMG_GetHeight', 'gm_u16 (VmImageType *)'),
        0x038: ('IMG_GetWidth', 'gm_u16 (VmImageType *)'),
        0x03c: ('ToRGB', 'gm_u16 ('),
        0x040: ('DrawLine', 'void ('),
        0x044: ('DrawLineEx', 'void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_u16)'),
        0x048: ('DrawRect', 'void (VmGraphics *, gm_s16, gm_s16, gm_s16, gm_s16, gm_u16)'),
        0x04c: ('FillRect', 'void (VmGraphics *, gm_s16, gm_s16, gm_u16, gm_u16, gm_u16)'),
        0x050: ('GetStreamDataFormRes', 'gm_u8 *(tResource)'),
        0x054: ('GetClip', 'GAME_RECT_T ()'),
        0x058: ('CheckClip', 'void (gm_s16, gm_s16)'),
        0x05c: ('GetFontWidth', 'int ()'),
        0x060: ('GetFontWidth_char', 'int ()'),
        0x064: ('GetFontHeight', 'int ()'),
        0x068: ('GetFontHeight_char', 'int ()'),
        0x06c: ('DrawImageWithClipEx', 'void (VmImageType *, VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x070: ('DrawImageClipAndAlphaEx', 'void (VmImageType *, VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x074: ('DrawImageNumberEx', 'void (VmImageType *, VmImageType *, gm_s32, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_u8)'),
        0x078: ('RefresScreen', 'void ()'),
        0x07c: ('NumToZhiFei', 'gm_u8 *(gm_u8)'),
        0x080: ('GetLCDBuffer', 'gm_u16 *()'),
        0x084: ('InitTextBox', 'void ('),
        0x088: ('getTextLine', 'gm_s32 (char *, gm_s32)'),
        0x08c: ('InitSprite', 'void ('),
        0x090: ('initListener', 'void ('),
        0x094: ('releaseListener', 'void (Listener *)'),
        0x098: ('talkRepaintListener', 'void (Listener *, gm_s16, gm_s16, gm_s16, gm_s16)'),
        0x09c: ('initTalker', 'void ('),
    },
    'VmGameUtilManagerTag': {
        0x000: ('CdRect', 'gm_bool (int, int, int, int, int, int, int, int)'),
        0x004: ('CdRectPoint', 'gm_bool (int, int, int, int, int, int)'),
        0x008: ('CdRect2', 'gm_bool (int, int, int, int, int, int, int, int)'),
        0x00c: ('CdRectPoint2', 'gm_bool (int, int, int, int, int, int)'),
        0x010: ('Abs', 'gm_s16 (gm_s16)'),
        0x014: ('Max', 'gm_s16 (gm_s16, gm_s16)'),
        0x018: ('Min', 'gm_s16 (gm_s16, gm_s16)'),
        0x01c: ('Random', 'gm_s16 (gm_s16, gm_s16)'),
        0x020: ('Sqrt', 'gm_s32 (gm_s32)'),
        0x024: ('DF_SetDataPackage', 'void (DF_DataPackage *)'),
        0x028: ('DF_GetDataPackage', 'DF_DataPackage *()'),
        0x02c: ('DF_GetResourceByResourceID', 'char *(int)'),
        0x030: ('DF_GetResourceByFileName', 'char *(char *)'),
        0x034: ('DF_GetResourceNameByID', 'char *(int)'),
        0x038: ('DF_GetResourceIDByFileName', 'int (char *)'),
        0x03c: ('DF_GetTResource', 'tResource (char *)'),
        0x040: ('DF_GetStreamTResource', 'tResource (char *)'),
        0x044: ('DF_DataPackage_ShowFileList', 'void ()'),
        0x048: ('DF_String_Equal', 'gm_bool (char *, char *)'),
        0x04c: ('ReadShort', 'gm_s16 (char *'),
        0x050: ('DF_ReadInt', 'gm_s32 (char *, gm_s32 *)'),
        0x054: ('DF_File_ReadShort', 'gm_s16 (VMFILE)'),
        0x058: ('DF_File_ReadInt', 'gm_s32 (VMFILE)'),
        0x05c: ('DF_WriteShort', 'void (char *, gm_s32 *'),
        0x060: ('DF_WriteInt', 'void (char *, gm_s32 *, gm_s32)'),
        0x064: ('DF_ReadString', 'char *(char *, gm_s32 *)'),
        0x068: ('DF_ReadStringEx', 'void ('),
        0x06c: ('DF_File_ReadString', 'char *(VMFILE)'),
        0x070: ('DF_File_ReadToBuffer', 'void (VMFILE, char *, gm_s32)'),
        0x074: ('DF_ReadString2', 'char *(char *, gm_s32 *)'),
        0x078: ('DF_GetMemoryBlock', 'MemoryBlock *()'),
        0x07c: ('DF_Sin', 'gm_s32 (gm_s32)'),
        0x080: ('DF_Cos', 'gm_s32 (gm_s32)'),
        0x084: ('DF_Degree', 'gm_s32 (gm_s32, gm_s32)'),
        0x088: ('DF_CollectionTest', 'gm_bool (Rect, Rect)'),
        0x08c: ('DF_SwapVal', 'void ('),
        0x090: ('formatString', 'char *(const void *, ...)'),
        0x094: ('Storage_Date', 'gm_bool (char *, gm_u8 *, int, gm_bool, gm_bool)'),
        0x098: ('Game_stricmp', 'gm_u32 (char *, char *)'),
        0x09c: ('Game_strnicmp', 'gm_u32 (char *, char *, int)'),
    },
    'VmImManagerTag': {
        0x000: ('reserver_func01', 'void (void *)'),
        0x004: ('reserver_func02', 'void (void *)'),
        0x008: ('reserver_func03', 'void (void *)'),
        0x00c: ('reserver_func04', 'void (void *)'),
        0x010: ('reserver_func05', 'void (void *)'),
        0x014: ('reserver_func06', 'void (void *)'),
        0x018: ('reserver_func07', 'void (void *)'),
        0x01c: ('reserver_func08', 'void (void *)'),
    },
    'VmIoManagerTag': {
        0x000: ('Vm_file_open', 'VMFILE (VmFileDevType'),
        0x004: ('Vm_file_close', 'void (VMFILE)'),
        0x008: ('Vm_file_exist', 'VMBOOLEAN (VmFileDevType, const VMUINT16 *)'),
        0x00c: ('Vm_file_direxist', 'VMBOOLEAN (VmFileDevType, const VMUINT16 *)'),
        0x010: ('Vm_file_read', 'VMUINT32 ('),
        0x014: ('Vm_file_write', 'VMUINT32 (void *, VMUINT32, VMFILE)'),
        0x018: ('Vm_file_seek', 'VMINT32 (VMFILE, VMINT32, VMINT32)'),
        0x01c: ('Vm_file_tell', 'VMINT32 (VMFILE)'),
        0x020: ('Vm_file_getfilesize', 'VMINT32 (VMFILE)'),
        0x024: ('Vm_file_delete', 'VMINT32 (VmFileDevType, const VMUINT16 *)'),
        0x028: ('Vm_file_rename', 'VMINT32 (VmFileDevType, const VMUINT16 *, const VMUINT16 *)'),
        0x02c: ('Vm_file_mkdir', 'VMINT32 (VmFileDevType, const VMUINT16 *)'),
        0x030: ('Vm_file_rmdir', 'VMINT32 (VmFileDevType, const VMUINT16 *)'),
        0x034: ('Vm_find_first', 'VMINT32 (VmFileDevType, const VMUINT16 *, const VMUINT16 *'),
        0x038: ('Vm_find_next', 'VMINT32 (VmFileDevType, VMINT32, const VMUINT16 *, VMUINT16 *)'),
        0x03c: ('Vm_find_close', 'void (VMINT32)'),
        0x040: ('Vm_get_freespace', 'VMUINT32 ()'),
        0x044: ('Vm_get_sdcardStatus', 'VMBOOLEAN ()'),
        0x048: ('Vm_GetFilenameFromPath', 'void (VMUINT16 *, VMBOOLEAN, VMUINT16, VMUINT16 *)'),
        0x04c: ('Vm_file_getMp3Dir', 'VMUINT16 *()'),
        0x050: ('Vm_file_getMp4Dir', 'VMUINT16 *()'),
        0x054: ('Vm_file_getPicDir', 'VMUINT16 *()'),
        0x058: ('Vm_file_getBookDir', 'VMUINT16 *()'),
        0x05c: ('Vm_file_truncate', 'VMINT32 (VMINT32)'),
        0x060: ('vm_file_RdWt', 'VMBOOLEAN ('),
        0x064: ('Vm_file_getSysDir', 'VMUINT16 *()'),
        0x068: ('Vm_fmgr_select_entry', 'void ('),
        0x06c: ('Vm_get_freespace_ex', 'VMUINT32 (VmFileDevType)'),
        0x070: ('Vm_get_sdcardStatusEx', 'VMBOOLEAN ()'),
        0x074: ('Vm_get_fullname', 'void (VmFileDevType, const VMUINT16 *, VMUINT16 *)'),
    },
    'VmLcdManagerTag': {
        0x000: ('VMGetCurrMainScreenImage', 'VmImageType *()'),
        0x004: ('VMGetLCDBuffer', 'VMUINT16 *()'),
        0x008: ('VM_InvalidateLcd', 'void ()'),
        0x00c: ('VMGetCurrFontType', 'VmFontType ()'),
        0x010: ('VMSetCurrFontType', 'void (VmFontType)'),
        0x014: ('VMGetFontWidth', 'VMUINT16 (VMBOOLEAN)'),
        0x018: ('VMGetFontHeight', 'VMUINT16 (VMBOOLEAN)'),
        0x01c: ('VMGetStringWidth', 'VMUINT16 (VMSTR)'),
        0x020: ('VMGetStringHeight', 'VMUINT16 (VMSTR)'),
        0x024: ('VMDrawString', 'void (VMSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x028: ('VMDrawStringEx', 'void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x02c: ('VMDrawStringClipAlign', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)'),
        0x030: ('VMDrawStringClip', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x034: ('VMDrawStringRect', 'VMUINT32 (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x038: ('VMDrawLineEx', 'VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x03c: ('VMDrawLine', 'VMBOOLEAN (VmPointType, VmPointType, VMUINT16)'),
        0x040: ('VMDrawRect', 'VMBOOLEAN (VmRectType, VMUINT16)'),
        0x044: ('VMDrawRectEx', 'VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x048: ('VMFillRect', 'VMBOOLEAN (VmRectType, VMUINT16)'),
        0x04c: ('VMFillRectEx', 'VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x050: ('vMFillRectWithImage', 'VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmImageType *)'),
        0x054: ('vMFillRectWithImageEx', 'VMBOOLEAN (VmImageType *, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmImageType *)'),
        0x058: ('VMCreateImage', 'VMBOOLEAN (VMUINT16, VmImageType *)'),
        0x05c: ('VMCreateImageFromInRes', 'VMBOOLEAN (VMUINT16, VmImageType *)'),
        0x060: ('VMDrawImageWithClipEx', 'void (VmImageType *, VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)'),
        0x064: ('VMDrawImageClipAndAlphaEx', 'void (VmImageType *, VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)'),
        0x068: ('VMDrawImage', 'VMBOOLEAN (VmImageType *, VmPointType)'),
        0x06c: ('VMDrawImageEx', 'VMBOOLEAN (VmImageType *, VMUINT16, VMUINT16)'),
        0x070: ('VMDrawImageWithAlpha', 'VMBOOLEAN (VmImageType *, VmPointType)'),
        0x074: ('VMDrawImageWithClip', 'VMBOOLEAN (VmImageType *, VmPointType, VmRectType)'),
        0x078: ('VMDrawImageWithClip2', 'VMBOOLEAN (VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)'),
        0x07c: ('VMDrawImageClipAndAlpha', 'VMBOOLEAN (VmImageType *, VmPointType, VmRectType)'),
        0x080: ('VMDrawImageClipAndAlpha2', 'VMBOOLEAN (VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)'),
        0x084: ('VMGetImageWidth', 'VMUINT16 (VmImageType *)'),
        0x088: ('VMGetImageHeight', 'VMUINT16 (VmImageType *)'),
        0x08c: ('VMDestoryImage', 'VMBOOLEAN (VmImageType *)'),
        0x090: ('VMIsBacklightOn', 'VMBOOLEAN ()'),
        0x094: ('VMCtrlBacklight', 'void (VMBOOLEAN)'),
        0x098: ('VMGB2UCS2', 'VMUINT16 (VMSTR, VMWSTR, VMUINT16)'),
        0x09c: ('VMUCS2GB', 'VMUINT16 (VMWSTR, VMSTR, VMUINT16)'),
        0x0a0: ('VMWinPointIsInRect', 'VMBOOLEAN (VmPointType, VmRectType)'),
        0x0a4: ('vmResGetTxtWithDataPackage', 'VMCHAR *(VMUINT32'),
        0x0a8: ('VmResGetDefTxt', 'VMCHAR *(VMUINT32)'),
        0x0ac: ('vmResGetTxtForGame', 'VMCHAR *(VMUINT32)'),
        0x0b0: ('IMG_InitDataPage', 'void (tResource, gm_s16)'),
        0x0b4: ('IMG_InitInnerDataPageEx', 'void (tResource)'),
        0x0b8: ('IMG_ReleaseDataPage', 'void ()'),
        0x0bc: ('IMG_InitDataPageEx', 'void (tResource, gm_s16, DF_DataPackage *)'),
        0x0c0: ('IMG_CreateImageFormIdEx', 'VmImageType *(gm_u32, DF_DataPackage *, VmImageType *)'),
        0x0c4: ('IMG_CreateImageFormStream', 'VmImageType *('),
        0x0c8: ('VMDrawStandardImage', 'void (VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32'),
        0x0cc: ('VMGetStandardImageDimension', 'void (VMUINT8 *, VMUINT32, VMUINT8'),
        0x0d0: ('VMGetStandardImageType', 'void (VMUINT8 *, VMUINT8 *)'),
        0x0d4: ('VMDrawStandardImageEx', 'void (VmImageType *, VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)'),
        0x0d8: ('vMDrawStringBorder', 'void (VMSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x0dc: ('vMDrawStringClipAlignBorder', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)'),
        0x0e0: ('vMDrawStringClipBorder', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x0e4: ('IMG_InitDataPageTxt', 'void (gm_u32)'),
        0x0e8: ('vMImageDecoderAllocMemory', 'void (VMUINT32'),
        0x0ec: ('vMImageDecoderFreeMemory', 'void (void **)'),
        0x0f0: ('vMImageDecoderGetImageData', 'VMUINT8 *('),
        0x0f4: ('vMImageDecoderRegImageCodecHandler', 'void (GddiImageFormat'),
        0x0f8: ('VMGetCharWidth', 'VMUINT16 (VMUINT16)'),
        0x0fc: ('vMDrawUcs2String', 'void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x100: ('vMDrawUcs2StringBorder', 'void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x104: ('vMDrawUcs2StringEx', 'void (VmImageType *, VMUWSTR, VMUINT16, VMUINT16, VMUINT16)'),
        0x108: ('vMDrawUcs2StringClipAlignBorder', 'VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)'),
        0x10c: ('vMDrawUcs2StringClipAlign', 'VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)'),
        0x110: ('vMDrawUcs2StringClipBorder', 'VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x114: ('vMDrawUcs2StringClip', 'VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x118: ('vMDrawUcs2StringRect', 'VMUINT32 (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x11c: ('vMGetUcs2StringWidth', 'VMUINT16 (VMUWSTR)'),
        0x120: ('vMGetUcs2StringHeight', 'VMUINT16 (VMUWSTR)'),
        0x124: ('VmAllowBackLight', 'void (VMBOOLEAN)'),
        0x128: ('VmGetIsNeedRefreshLcd', 'VMBOOLEAN ()'),
        0x12c: ('VmSetIsNeedRefreshLcd', 'void (VMBOOLEAN)'),
        0x130: ('VmLCDInvalidateRectEnable', 'void (VMBOOLEAN)'),
        0x134: ('VmSetVideoIsNeedClosed', 'void (VMBOOLEAN)'),
        0x138: ('VmGetVideoIsNeedClosed', 'VMBOOLEAN ()'),
        0x13c: ('vMDrawUcs2StringRectEx', 'void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)'),
        0x140: ('vMSetCbeFontDataPtr', 'void ('),
        0x144: ('vMGetFontHeightEx', 'VMUINT16 (VMBOOLEAN, VmFontType)'),
        0x148: ('vMGetFontWidthEx', 'VMUINT16 (VMBOOLEAN, VmFontType)'),
        0x14c: ('vMGetStringHeightEx', 'VMUINT16 (VMSTR, VmFontType)'),
        0x150: ('vMGetStringWidthEx', 'VMUINT16 (VMSTR, VmFontType)'),
        0x154: ('vMShowStringEx', 'void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16, VmFontType)'),
        0x158: ('vMShowString', 'void (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmFontType)'),
        0x15c: ('vMShowStringClipAlign', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16, VmFontType)'),
        0x160: ('vMShowStringClip', 'VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmFontType)'),
        0x164: ('vMShowStringRect', 'VMUINT32 (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmFontType)'),
        0x168: ('vM_InvalidateLcdEx', 'void (VMINT32, VMINT32, VMINT32, VMINT32)'),
        0x16c: ('vMSetFontSize', 'void (VMUINT32)'),
        0x170: ('vMResetFontSize', 'void ()'),
        0x174: ('vMUTF82UCS2', 'VMUINT16 (VMSTR, VMWSTR)'),
        0x178: ('vMUCS2UTF8', 'VMUINT16 (VMWSTR, VMSTR)'),
    },
    'VmManagerTag': {
        0x000: ('VMInitIoManager', 'void ('),
        0x004: ('VMGetIoManager', 'VmIoManager *()'),
        0x008: ('VMInitLcdManager', 'void ('),
        0x00c: ('VMGetLcdManager', 'VmLcdManager *()'),
        0x010: ('VMInitTimeManager', 'void ('),
        0x014: ('VMGetTimeManager', 'VmTimeManager *()'),
        0x018: ('VMInitCtrlManager', 'void ('),
        0x01c: ('VMGetCtrlManager', 'VmCtrlManager *()'),
        0x020: ('VMInitMemoryManager', 'void ('),
        0x024: ('VMGetMemoryManager', 'VmMemoryManager *()'),
        0x028: ('VMInitBillingManager', 'void ('),
        0x02c: ('VMGetBillingManager', 'VmBillingManager *()'),
        0x030: ('VMInitScreenManager', 'void ('),
        0x034: ('VMGetScreenManager', 'VmScreenManager *()'),
        0x038: ('VMInitNetManager', 'void ('),
        0x03c: ('VMGetNetManager', 'VmNetManager *()'),
        0x040: ('VMInitUcs2StrManager', 'void ('),
        0x044: ('VMGetUcs2StrManager', 'VmUcs2StrManager *()'),
        0x048: ('VMInitSysManager', 'void ('),
        0x04c: ('VMGetSysManager', 'VmSysManager *()'),
        0x050: ('VMInitDFScriptManager', 'void ('),
        0x054: ('VMGetDFScriptManager', 'VmDFScriptManager *()'),
        0x058: ('VMInitGameLcdManager', 'void ('),
        0x05c: ('VMGetGameLcdManager', 'VmGameLcdManager *()'),
        0x060: ('VMInitGameUtilManager', 'void ('),
        0x064: ('VMGetGameUtilManager', 'VmGameUtilManager *()'),
        0x068: ('VMInitDFEnginelManager', 'void ('),
        0x06c: ('VMGetDFEnginelManager', 'VmDFEnginelManager *()'),
        0x070: ('VMInitNetAppManager', 'void ('),
        0x074: ('VMGetNetAppManager', 'VmNetAppManager *()'),
        0x078: ('VMInitAudioManager', 'void ('),
        0x07c: ('VMGetAudioManager', 'VmAudioManager *()'),
        0x080: ('VMInitGameManagerOld', 'void (void *)'),
        0x084: ('VMGetGameManagerOld', 'void *()'),
        0x088: ('VMInitManager', 'void ('),
        0x08c: ('vMInitGSensorManager', 'void ('),
        0x090: ('vMGetGSensorManager', 'VmGSensorManager *()'),
        0x094: ('vMInitVmStdManager', 'void ('),
        0x098: ('vMGetVmStdManager', 'VmStdManager *()'),
        0x09c: ('vMInitDlLoadManager', 'void ('),
        0x0a0: ('vMGetDlLoadManager', 'VmDlLoadManager *()'),
        0x0a4: ('vMGetDlRsManager', 'VmDlResourceManager *()'),
        0x0a8: ('vMInitDlRsManager', 'void (VmDlResourceManager *)'),
        0x0ac: ('vMGetDlImageManager', 'VmDlImageManager *()'),
        0x0b0: ('vMInitDlImageManager', 'void (VmDlImageManager *)'),
        0x0b4: ('vMInitVmImManager', 'void ('),
        0x0b8: ('vMGetVmImManager', 'VmImManager *()'),
        0x0bc: ('vMInitTencentQQManager', 'void ('),
        0x0c0: ('vMInitQQIdleManager', 'void (void *)'),
        0x0c4: ('VmInitVideoManager', 'void ('),
        0x0c8: ('VmGetVideoManager', 'VmVideoManager *()'),
        0x0cc: ('VmGetDlWPayManager', 'VmDLWPayManager *()'),
        0x0d0: ('vMInitEmailIdleManager', 'void (void *)'),
    },
    'VmMemoryManagerTag': {
        0x000: ('dF_InitMemory', 'void (gm_u32)'),
        0x004: ('dF_ReleaseMemory', 'void ()'),
        0x008: ('dF_Malloc_In', 'VMBOOLEAN (void **, gm_u32)'),
        0x00c: ('dF_Free', 'void (void **)'),
        0x010: ('dF_Memory_gc', 'void ()'),
        0x014: ('mF_InitMemoryBlock', 'void ('),
        0x018: ('mF_MemoryBlock_Malloc', 'void *(MemoryBlock *, gm_s32)'),
        0x01c: ('mF_MemoryBlock_Reset', 'void (MemoryBlock *)'),
        0x020: ('mF_GetGMemoryBlockPtr', 'MemoryBlock *()'),
        0x024: ('mF_InitGmemoryBlock', 'void (gm_s32)'),
        0x028: ('mF_ReleaseGmemoryBlock', 'void ()'),
        0x02c: ('mF_resetGmemoryBlock', 'void ()'),
        0x030: ('mF_MallocGmemoryBlock', 'void *(gm_s32)'),
        0x034: ('mallocBigMen', 'void *(int)'),
        0x038: ('freeBigMen', 'void (void *)'),
        0x03c: ('DF_Memory_AttachPointer', 'void (void **, void **)'),
        0x040: ('mF_MemoryBlock_Release', 'void (MemoryBlock *)'),
        0x044: ('dF_InitMemoryEx', 'void (gm_u32)'),
        0x048: ('RemallocBigMen', 'void *(void *, int)'),
        0x04c: ('dF_Malloc_debug', 'VMBOOLEAN (void **, gm_u32, const char *, int)'),
        0x050: ('mallocBigMen_debug', 'void *(VMUINT32, const char *, int)'),
        0x054: ('getShareMemAlloced', 'VMUINT32 ()'),
        0x058: ('mallocBigMen2', 'void *(int)'),
        0x05c: ('freeBigMen2', 'void (void *)'),
        0x060: ('GetBlockMemInfo', 'void (VMUINT32 *'),
        0x064: ('mallocSysMem', 'void *(VMUINT32)'),
        0x068: ('freeSysMen', 'void (void *)'),
    },
    'VmNetAppManagerTag': {
        0x000: ('coolbar_NetEntry', 'void ('),
        0x004: ('coolbar_GHEntry', 'void ('),
        0x008: ('net_SetCommonHandle', 'void (NetCommonHandleF)'),
        0x00c: ('net_set_appPackage_dataSegment', 'void (const char *, const char *, VMUINT8 *, VMUINT16 *)'),
        0x010: ('net_set_appPackage_dataSegmentExt', 'void (const char *, VMUINT32, VMUINT8 *, VMUINT16 *)'),
        0x014: ('net_set_appPackage_dataSegment_combi', 'void (const char *, const char *, VMUINT8 *, VMUINT16, VMUINT16 *)'),
        0x018: ('net_Game_Send_AppPackage', 'VMBOOLEAN (VMUINT8 *, VMUINT16, VMUINT8, VMUINT8)'),
        0x01c: ('net_Game_Send_gamePackage', 'VMBOOLEAN (VMUINT8 *, VMUINT16)'),
        0x020: ('net_Game_get_userId', 'VMUINT32 ()'),
        0x024: ('net_Game_set_userId', 'void (VMUINT32)'),
        0x028: ('net_Game_set_sessionId', 'void (VMUINT8 *, VMUINT8)'),
        0x02c: ('net_Game_get_gameId', 'VMUINT32 ()'),
        0x030: ('net_Game_set_gameId', 'void (VMUINT32)'),
        0x034: ('net_Game_get_gameType', 'VMUINT8 ()'),
        0x038: ('net_Game_set_gameType', 'void (VMUINT8)'),
        0x03c: ('net_Game_get_gamePackageType', 'VMUINT8 ()'),
        0x040: ('net_Game_set_gamePackageType', 'void (VMUINT8)'),
        0x044: ('net_Game_get_gameStep', 'VMUINT8 ()'),
        0x048: ('net_Game_set_gameStep', 'void (VMUINT8)'),
        0x04c: ('net_get_connectId', 'VMINT32 ()'),
        0x050: ('net_set_connectId', 'void (VMINT32)'),
        0x054: ('net_Game_Init', 'void (VMUINT8, VMUINT8)'),
        0x058: ('net_Game_Exit', 'void (VMUINT8)'),
        0x05c: ('net_Game_ready', 'void (VMUINT8)'),
        0x060: ('net_Game_sitDown', 'void (VMUINT8, VMUINT8, VMUINT16)'),
        0x064: ('net_Game_send_select_score', 'void (VMUINT8, VMUINT8)'),
        0x068: ('net_Game_pass', 'void (VMUINT8)'),
        0x06c: ('net_Game_combine_card', 'void (VMUINT8 *, VMUINT8, VMUINT8)'),
        0x070: ('net_Game_parse_card_value', 'void (VMUINT8'),
        0x074: ('net_Game_combine_card_value', 'void (CCard, VMUINT8 *)'),
        0x078: ('net_Game_get_cards', 'void (GAME_CARDS, VMUINT8 *, VMUINT8 *, VMUINT8 *, VMUINT8)'),
        0x07c: ('net_close_channel', 'void (VMINT32)'),
        0x080: ('net_Game_set_curRmIndex', 'void (VMUINT16)'),
        0x084: ('net_Game_get_curRmIndex', 'VMUINT16 ()'),
        0x088: ('net_Game_set_curSerIndex', 'void (VMUINT16)'),
        0x08c: ('net_Game_get_curSerIndex', 'VMUINT16 ()'),
        0x090: ('net_game_request_personalBasicInfo', 'void (VMUINT32)'),
        0x094: ('net_game_request_personalGameInfo', 'void (VMUINT32, VMUINT8)'),
        0x098: ('net_game_request_personalBGInfo', 'void (VMUINT32, VMUINT8)'),
        0x09c: ('net_get_DefaultLoginInfo', 'void (LOGIN_INFO_T *)'),
        0x0a0: ('net_write_DefaultLoginInfo', 'void (LOGIN_INFO_T *)'),
        0x0a4: ('net_Recv_Data', 'void (VMUINT8 *, VMUINT32, VMUINT32, NetRequestResultType)'),
        0x0a8: ('net_build_sessionId', 'void (VMINT32)'),
        0x0ac: ('net_Login', 'void ('),
        0x0b0: ('net_commonRegister', 'VMBOOLEAN (VMCHAR *, VMINT32, VMCHAR *, VMCHAR *)'),
        0x0b4: ('net_OneKeyRegister', 'VMBOOLEAN (VMCHAR *, VMINT32)'),
        0x0b8: ('net_set_UserInfo', 'void ('),
        0x0bc: ('net_get_UserInfo', 'USER_BASIC_INFO *()'),
        0x0c0: ('net_parse_Int8_by_name', 'VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT8 *)'),
        0x0c4: ('net_parse_Int16_by_name', 'VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT16 *)'),
        0x0c8: ('net_parse_Int32_by_name', 'VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT32 *)'),
        0x0cc: ('net_parse_Str_by_name', 'VMUINT8 (VMUINT8 *, VMUINT16, const char *, VMUINT8 *, VMUINT16 *)'),
        0x0d0: ('net_set_serverVer', 'void (VMUINT16)'),
        0x0d4: ('net_get_serverVer', 'VMUINT16 ()'),
        0x0d8: ('net_parse_signedInt32_by_name', 'VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMINT32 *)'),
        0x0dc: ('net_get_valueData_offset_by_name', 'VMUINT8 (VMUINT8 *, VMUINT16, const char *, VMUINT32 *, VMUINT16 *)'),
        0x0e0: ('net_set_redirectURL', 'void (char *, VMUINT16)'),
        0x0e4: ('net_get_redirectURL', 'char *()'),
        0x0e8: ('net_Game_Send_AppPackage_NewConnect', 'VMBOOLEAN (VMUINT32, VMUINT8 *, VMUINT16, VMUINT8, VMUINT8)'),
        0x0ec: ('net_Recv_Data_NewConnect', 'void (VMUINT8 *, VMUINT32, VMUINT32, NetRequestResultType, VMUINT32)'),
        0x0f0: ('net_GetAppInfo', 'void (VMUINT16 *, VMUINT16 *, VMUINT8 *)'),
    },
    'VmNetManagerTag': {
        0x000: ('OpenChannel', 'VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *)'),
        0x004: ('SendData', 'VMBOOLEAN (VMUINT32, VMUINT32, VMUINT8 *)'),
        0x008: ('CloseChannel', 'VMBOOLEAN (VMUINT32)'),
        0x00c: ('GetHttpData', 'VMBOOLEAN (char *, NetCallBackType, VMUINT32 *)'),
        0x010: ('PostHttpData', 'VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *)'),
        0x014: ('CancelHttpConnect', 'VMBOOLEAN (VMINT32)'),
        0x018: ('OpenChannel2', 'VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType2, VMUINT32 *)'),
        0x01c: ('OpenQQChannel', 'VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *)'),
        0x020: ('VMGetLinkSetNum', 'VMUINT8 ()'),
        0x024: ('VMGetLinkSetNameByIndex', 'VMUINT16 (VMUINT8, char *, VMUINT8)'),
        0x028: ('VMGetWapIndex', 'VMUINT8 ()'),
        0x02c: ('VMGetNetIndex', 'VMUINT8 ()'),
        0x030: ('SetWapIndex', 'void (VMUINT8)'),
        0x034: ('SetNetIndex', 'void (VMUINT8)'),
        0x038: ('GetGateWayByIndex', 'VMUINT8 *(VMUINT8)'),
        0x03c: ('GetPortByIndex', 'VMUINT16 (VMUINT8)'),
        0x040: ('GetApnByIndex', 'VMUINT8 *(VMUINT8)'),
        0x044: ('GetHttpDataEx', 'VMBOOLEAN (char *, NetCallBackType, VMUINT32 *, VMCHAR *, VMCHAR *, VMBOOLEAN, HTTP_PAGE_GETTYPE)'),
        0x048: ('OpenChannelEx', 'VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *, VMCHAR *, VMBOOLEAN)'),
        0x04c: ('PostHttpDataEx', 'VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *, VMCHAR *, VMCHAR *, VMBOOLEAN, HTTP_PAGE_GETTYPE)'),
        0x050: ('GetGprsStatus', 'VM_GPRS_STATE_E ()'),
        0x054: ('SetGprsStatus', 'void (VM_GPRS_STATE_E)'),
        0x058: ('GetCurApn', 'void (VMCHAR *)'),
        0x05c: ('GetDeactiveFlag', 'VMUINT8 ()'),
        0x060: ('SetDeactiveFlag', 'void (VMUINT8)'),
        0x064: ('SetStartPos', 'VMUINT32 (VMUINT32)'),
        0x068: ('GetUAAgent', 'void (VMCHAR *)'),
        0x06c: ('GetWapProfile', 'void (VMCHAR *)'),
        0x070: ('GetLastNetError', 'VMUINT16 ()'),
        0x074: ('GetHttpMassData', 'VMBOOLEAN (char *, NetCallBackType, VMUINT32 *'),
        0x078: ('PostHttpMassData', 'VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *, MassDataSendingPara *)'),
        0x07c: ('VMIsWifiReady', 'VMBOOLEAN ()'),
        0x080: ('VMGetGPRSCounter', 'void ('),
        0x084: ('VmSetSockQueryTime', 'void (VMUINT32)'),
        0x088: ('VmResetSockQueryTime', 'void ()'),
        0x08c: ('VmNetDataReset', 'void ()'),
        0x090: ('VmGetNetData', 'void (VMUINT32 *, VMUINT32 *)'),
        0x094: ('VmGetFlowMassage', 'void ('),
        0x098: ('VmClearFlowMassage', 'VMBOOLEAN (VMUINT16)'),
        0x09c: ('VmDeleteFlowMassage', 'VMBOOLEAN (VMUINT16)'),
        0x0a0: ('VmGetSingleFlowmsg', 'VMBOOLEAN (VMUINT16, FlowMsg **)'),
        0x0a4: ('VmClearAllFlowMassage', 'void ()'),
        0x0a8: ('VmDeleteAllFlowMassage', 'void ()'),
    },
    'VmScreenManagerTag': {
        0x000: ('vmSCREEN_ChangeScreen', 'void ('),
        0x004: ('vmSCREEN_NotifyLoadResource', 'void (tScreen *)'),
        0x008: ('vmChangeScreen', 'void ('),
        0x00c: ('vmChangeScreenEx', 'void (VmScreen *, void *, VMBOOLEAN)'),
        0x010: ('vmAddScreen', 'void (VmScreen *)'),
        0x014: ('vmAddScreenEx', 'void (VmScreen *, void *, VMBOOLEAN)'),
        0x018: ('vmDeleteScreen', 'void (VmScreen *)'),
        0x01c: ('vmScreenLoadResource', 'void (VmScreen *)'),
        0x020: ('vmScreenLoadResourceEx', 'void (VmScreen *, void *)'),
        0x024: ('vmIsScreenFocus', 'VMBOOLEAN (VmScreen *)'),
        0x028: ('vmIsBottomScreen', 'VMBOOLEAN (VmScreen *)'),
        0x02c: ('vmScreenLogic', 'void (VMUINT32, void *)'),
    },
    'VmStdManagerTag': {
        0x000: ('memcpy', 'void *(void *, const void *, unsigned int)'),
        0x004: ('strlen', 'unsigned int (const char *)'),
        0x008: ('memset', 'void *(void *, int, unsigned int)'),
        0x00c: ('sprintf', 'int (char *, const char *, ...)'),
        0x010: ('printf', 'void (char *, ...)'),
        0x014: ('rand', 'int ()'),
        0x018: ('vsprintf', 'int (char *, const char *'),
        0x01c: ('strncpy', 'char *(char *, const char *, unsigned int)'),
        0x020: ('strcpy', 'char *(char *, const char *)'),
        0x024: ('strcat', 'char *(char *, const char *)'),
        0x028: ('atol', 'long (const char *)'),
        0x02c: ('memmove', 'void *(void *, const void *, unsigned int)'),
        0x030: ('atoi', 'int (const char *)'),
        0x034: ('pow', 'float (float, float)'),
        0x038: ('strcmp', 'int (const char *, const char *)'),
        0x03c: ('memcmp', 'int (const void *, const void *, size_t)'),
        0x040: ('strncmp', 'int (const char *, const char *, size_t)'),
        0x044: ('setjmp', 'int (int *)'),
        0x048: ('longjmp', 'void (int *, int)'),
        0x04c: ('atof', 'double (const char *)'),
        0x050: ('vMstricmp', 'VMUINT32 (char *, char *)'),
        0x054: ('vMstrnicmp', 'VMUINT32 (char *, char *, int)'),
    },
    'VmSysManagerTag': {
        0x000: ('VMIsSimReady', 'VMBOOLEAN ()'),
        0x004: ('VmSysIsHaveNetWork', 'VMBOOLEAN ()'),
        0x008: ('VMIsSystemReady', 'VMBOOLEAN ()'),
        0x00c: ('VMGetOperator', 'VmOperatorType ()'),
        0x010: ('VMGetIMEI', 'void (VMSTR, VMUINT32)'),
        0x014: ('VMGetIMSI', 'void (VMSTR, VMUINT32)'),
        0x018: ('VMGetPrjName', 'void (VMSTR, VMUINT32)'),
        0x01c: ('VMGetPrjVersion', 'void (VMSTR, VMUINT32)'),
        0x020: ('VMIsCallConnect', 'VMBOOLEAN ()'),
        0x024: ('VMIsDCopen', 'VMBOOLEAN ()'),
        0x028: ('VMGetStkCardStatus', 'VMBOOLEAN ()'),
        0x02c: ('VMGetActiveSim', 'VMUINT16 ()'),
        0x030: ('VmGetCoolbarlistInit', 'VMUINT8 ()'),
        0x034: ('VmSetFPS', 'void (VMUINT32)'),
        0x038: ('VmEnterWinClose', 'void ()'),
        0x03c: ('vMAudioIsSupportInCb', 'VMBOOLEAN ()'),
        0x040: ('vMAssert', 'void (char *, VMUINT32)'),
        0x044: ('GetCoolbarDirPath', 'VMUINT16 (VMUINT16 *)'),
        0x048: ('GetVerByAppID', 'VMUINT16 (VMUINT16)'),
        0x04c: ('GetCoolBarFullPath', 'void (VMUINT16 *, const char *)'),
        0x050: ('vMGSenserIsSupportInCb', 'VMBOOLEAN ()'),
        0x054: ('VmSendMsg', 'VMBOOLEAN (VMUINT16, VMUINT32, void *)'),
        0x058: ('vMGetKeyNum', 'VMUINT16 ()'),
        0x05c: ('vMIsSupportTP', 'VMBOOLEAN ()'),
        0x060: ('CDownGetCompany', 'void (VMUINT8 *, VMUINT16)'),
        0x064: ('CDownGetServicePhone', 'void (VMUINT8 *, VMUINT16)'),
        0x068: ('vMIsSupportIdleMenu', 'VMBOOLEAN ()'),
        0x06c: ('vMSendSms', 'VMBOOLEAN (VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN, SmSCallback)'),
        0x070: ('VmMakeCall', 'VMBOOLEAN (VMUINT8 *, VMUINT16)'),
        0x074: ('CDownGetData', 'VMUINT32 ('),
        0x078: ('GetCoolBarKernelCurrentVersion', 'VMUINT8 ()'),
        0x07c: ('CoolBar_DownLoad_GetFile', 'VMBOOLEAN (VMUINT16 *, char *, DownLoadStateCallBackType)'),
        0x080: ('CoolBar_DownLoad_Stop', 'void ()'),
        0x084: ('vmDlGetCurrAppId', 'VMUINT16 ()'),
        0x088: ('vmSysIsVisibleApp', 'VMBOOLEAN (VMUINT16)'),
        0x08c: ('cDownSetForceUpdate', 'void ()'),
        0x090: ('cDownGetModeAndVersion', 'void (VMUINT8 *, VMUINT16 *)'),
        0x094: ('mmiDynamicSetForceUpdate', 'void ()'),
        0x098: ('mmiDunamicGetModeAndVersion', 'void (VMUINT8 *, VMUINT16 *)'),
        0x09c: ('vMSwitchLog', 'void (VMBOOLEAN)'),
        0x0a0: ('Coolbar_GetResStatus', 'VMBOOLEAN (VMUINT16)'),
        0x0a4: ('coolbar_Update_Tfold', 'VMBOOLEAN (VMUINT16 *)'),
        0x0a8: ('CoolBar_EnterDmIn', 'void ()'),
        0x0ac: ('vmInputText', 'VMBOOLEAN (CBInputTextCallback'),
        0x0b0: ('vmInputPassword', 'VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)'),
        0x0b4: ('vmInputClose', 'void ()'),
        0x0b8: ('vmInputIsOpen', 'VMBOOLEAN ()'),
        0x0bc: ('VmRand', 'int ()'),
        0x0c0: ('VmSrand', 'void ('),
        0x0c4: ('VmGetSmsCenterNum', 'VMBOOLEAN (VMUINT8 *, VMUINT16)'),
        0x0c8: ('VmGetPrjCustom', 'void (VMSTR, VMUINT32)'),
        0x0cc: ('GetNetInfo', 'VMUINT8 ('),
        0x0d0: ('VmGetCbNum', 'VMUINT16 ()'),
        0x0d4: ('LzssEncode', 'void (VMUINT8 *, VMUINT32, VMUINT8 *'),
        0x0d8: ('LzssDecode', 'void (VMUINT8 *, VMUINT32, VMUINT8 *, VMUINT32 *)'),
        0x0dc: ('UpdateDmenu', 'void ()'),
        0x0e0: ('UpdateCDownmenu', 'void ()'),
        0x0e4: ('CbGetPlatfomName', 'VMCHAR *()'),
        0x0e8: ('VmInnerAppInfo', 'VMBOOLEAN ('),
        0x0ec: ('VmGetInnerAppIcon', 'VMBOOLEAN (VMUINT16, VMUINT8 *)'),
        0x0f0: ('CDownGetAppType', 'VMUINT8 (VMUINT16)'),
        0x0f4: ('vmSetGQQRunings', 'void (VMINT8)'),
        0x0f8: ('vmGetGQQRunings', 'VMINT8 ()'),
        0x0fc: ('vmGetQQAddress', 'void (VMUINT32 *, VMUINT32 *)'),
        0x100: ('VmGetScreenSize', 'VMUINT8 ()'),
        0x104: ('VmGetPlatformType', 'VMUINT8 ()'),
        0x108: ('VmDlGetIMEI', 'void (VMSTR, VMUINT32)'),
        0x10c: ('VmGetIMSI', 'void (VMSTR, VMUINT32)'),
        0x110: ('VmGetLoginInfo', 'void ('),
        0x114: ('VmSetLoginInfo', 'void (LOGIN_INFO_T *)'),
        0x118: ('VmGetAppNameByIdFromList', 'VMBOOLEAN (VMUINT16, VMUINT16 *)'),
        0x11c: ('VmUnInstallAppbyId', 'VMBOOLEAN (VMUINT16)'),
        0x120: ('VmGetDMenuFileName', 'void (VMUINT16 *)'),
        0x124: ('VmGetCDownFileName', 'void (VMUINT16 *)'),
        0x128: ('VmGetCDownAppUrl', 'void (char *, VMUINT8, VMUINT32)'),
        0x12c: ('VmDlGetPreAppId', 'VMUINT16 ()'),
        0x130: ('VmParseMixDownData', 'VMBOOLEAN (VMUINT16 *, VMUINT16 *)'),
        0x134: ('CoolBar_DownLoad_CBE', 'VMBOOLEAN (VMUINT16 *, char *, VMUINT32, DownLoadStateCallBackType)'),
        0x138: ('Coolbar_PreLoadApp', 'VMUINT8 (VMUINT16)'),
        0x13c: ('VmDlGetSpBf', 'VMUINT8 *()'),
        0x140: ('vMGetGameWinState', 'VMUINT8 ()'),
        0x144: ('VmGetHideText', 'VMCHAR *(VMCHAR *)'),
        0x148: ('VMPhbMultiSelectEntry', 'void (VMCHAR *, VMUINT16, VMUINT16, HandsetSelectCallback)'),
        0x14c: ('VmSetCurActiveSim', 'void (VMUINT8)'),
        0x150: ('VmGetAllSimStatus', 'void ('),
        0x154: ('VmSendMMS', 'VMBOOLEAN (VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN)'),
        0x158: ('VmGetFoucsWin', 'VMUINT32 ()'),
        0x15c: ('VmIsWinOpen', 'VMBOOLEAN (VMUINT32)'),
        0x160: ('VmIsInIdleWin', 'VMBOOLEAN ()'),
        0x164: ('VmIsInnerApp', 'VMBOOLEAN (VMUINT16)'),
        0x168: ('VmGetInnerAppVer', 'VMUINT16 (VMUINT16)'),
        0x16c: ('VmGetMixMenuLength', 'VMUINT32 ()'),
        0x170: ('VmGetMixMenudata', 'VMUINT8 *()'),
        0x174: ('VmGetWpayCBMInfo', 'void ('),
        0x178: ('vMGetCurVerAllInfo', 'VMUINT8 *()'),
        0x17c: ('VmSetFpsSleepFlag', 'void (VMBOOLEAN)'),
        0x180: ('vmSetSmsCenterNum', 'VMBOOLEAN (VMUINT8 *, VMUINT8)'),
        0x184: ('vmGetBuildTime', 'VMCHAR *()'),
        0x188: ('vmGetUsedTimes', 'VMUINT32 ()'),
        0x18c: ('VmSysGetBatteryInfo', 'void ('),
        0x190: ('VmSysSetLcdBright', 'void (VMUINT8)'),
        0x194: ('VmSysResetLcdBright', 'void ()'),
        0x198: ('VmSysSetPowerSaveMode', 'void (VMBOOLEAN)'),
        0x19c: ('VmGetOperatorMCC', 'VMUINT16 ()'),
        0x1a0: ('VmGetOperatorMNC', 'VMUINT16 ()'),
        0x1a4: ('VmGetSupportAppStore', 'VMBOOLEAN ()'),
        0x1a8: ('cDownGetCompanyEx', 'void (VMUINT8, VMUINT8 *, VMUINT16)'),
        0x1ac: ('VmSysGetCurrLcdLightInfo', 'void ('),
        0x1b0: ('VmSysStartVibration', 'void (VMINT32)'),
        0x1b4: ('VmSysStopVibration', 'void ()'),
        0x1b8: ('VmSysOpenBrowser', 'void (VMUINT16 *)'),
        0x1bc: ('VmSysSetSettingProfile', 'void (SETTING_PROFILE, VMUINT16 *, VMUINT16)'),
        0x1c0: ('VmSysGetSettingProfile', 'void (SETTING_PROFILE, VMUINT16 *, VMUINT16)'),
        0x1c4: ('VmSysGetSettingProfileName', 'void (SETTING_PROFILE, VMUINT16 *, VMUINT16)'),
        0x1c8: ('VmSysSaveContactPerson', 'VMBOOLEAN (VMUINT16 *, VMUINT8, VMUINT8 *, VMUINT8, phb_phonebook_type_t)'),
    },
    'VmTimeManagerTag': {
        0x000: ('VMStartTimer', 'VMUINT16 (VMUINT32, TimerCBPtr, void *)'),
        0x004: ('VMStopTimer', 'void (VMUINT16)'),
        0x008: ('VMGetTickCount', 'VMUINT32 ()'),
        0x00c: ('VMGetTotalSeconds', 'VMUINT32 ()'),
        0x010: ('VMGetCurrentTime', 'void ('),
        0x014: ('VMSysSleep', 'void (VMUINT32)'),
        0x018: ('VmSetSysTime', 'VMBOOLEAN (VMUINT8, VMUINT8, VMUINT8)'),
        0x01c: ('VmSetSysDate', 'VMBOOLEAN (VMUINT16, VMUINT8, VMUINT8)'),
        0x020: ('VMIncreaseTime', 'void (VmDateTimeType *, VmDateTimeType *, VmDateTimeType *)'),
        0x024: ('VMDecreaseTime', 'void (VmDateTimeType *, VmDateTimeType *, VmDateTimeType *)'),
    },
    'VmUcs2StrManagerTag': {
        0x000: ('VmutStrlenUcs2', 'VMUINT16 (const VMUINT16 *)'),
        0x004: ('VmutStrcpyUcs2', 'VMUINT16 *(VMUINT16 *, const VMUINT16 *)'),
        0x008: ('VmutStrcatUcs2', 'VMUINT16 *(VMUINT16 *, const VMUINT16 *)'),
        0x00c: ('VmutExpandStrcpy', 'VMUINT16 *(VMUINT16 *, const char *)'),
        0x010: ('VmutStrncpyUcs2', 'VMUINT16 *(VMUINT16 *, const VMUINT16 *'),
        0x014: ('VmutExpandStrncpy', 'VMUINT16 *(VMUINT16 *, const char *, const VMUINT32)'),
        0x018: ('VmutExpandMemcpy', 'void *(void *'),
        0x01c: ('VmutStrchrUcs2', 'VMUINT16 *(const VMUINT16 *, VMUINT16)'),
        0x020: ('VmutStrcmpUcs2', 'VMINT32 (const VMUINT16 *, const VMUINT16 *)'),
        0x024: ('VmutStricmpUcs2', 'VMINT32 (const VMUINT16 *, const VMUINT16 *)'),
        0x028: ('VmutStrncmpUcs2', 'VMINT32 (const VMUINT16 *, const VMUINT16 *, const VMUINT32)'),
    },
    'VmVideoManagerTag': {
        0x000: ('VmISPServiceOpen', 'void ()'),
        0x004: ('VmISPServiceClose', 'void ()'),
        0x008: ('VmDCVideoSetDisplayParam', 'VMUINT32 ('),
        0x00c: ('VmDCDisplayAFrame', 'VMUINT32 ('),
        0x010: ('VmVideoIRAMMemInit', 'void (VMUINT32, void *)'),
        0x014: ('VmVideoIRAMMemMalloc', 'void *(VMUINT32, VMUINT32)'),
        0x018: ('VmVideoIRAMMemFree', 'void (VMUINT32, VMUINT32)'),
        0x01c: ('VmVideoIRAMMemClose', 'void (VMUINT32, void *)'),
        0x020: ('VmCamOpenInit', 'VMBOOLEAN (void *)'),
        0x024: ('VmCloseCamera', 'VMBOOLEAN ()'),
        0x028: ('VmStartCaptureYUV', 'VMBOOLEAN (void *)'),
        0x02c: ('VmStopCaptureYUV', 'VMBOOLEAN ()'),
        0x030: ('VmIsDoubleCamera', 'VMBOOLEAN ()'),
        0x034: ('VmSetCameraLoc', 'void (VMBOOLEAN)'),
        0x038: ('VmVideoDecInit', 'void *(unsigned int)'),
        0x03c: ('VmVideoDecFrame', 'VMUINT32 (void *, const void *, VMUINT32, VMUINT32 *)'),
        0x040: ('VmVideoDecOutput', 'const void *(void *, void *, VMBOOLEAN)'),
        0x044: ('VmVideoDecOutputEx', 'const void *(void *, void *, void *, VMBOOLEAN)'),
        0x048: ('VmGetVideoDecParm', 'void (void *, VMUINT32 *, VMUINT32 *, VMUINT32 *)'),
        0x04c: ('VmGetVideoDecParmEx', 'void (void *, VMUINT32 *, VMUINT32 *, VMUINT32 *)'),
        0x050: ('VmVideoDecClose', 'void (void *)'),
        0x054: ('VmVideoEncInit', 'void *('),
        0x058: ('VmVideoEncFrame', 'VMUINT32 (void *, VMUINT8 *, VMUINT8 *, VMUINT32 *, VMUINT32 *)'),
        0x05c: ('VmVideoEncClose', 'void (void *)'),
        0x060: ('VmGetVideoEncParm', 'void (VMUINT32, VMUINT32 *, VMUINT32 *)'),
        0x064: ('VmVideoPicScaling', 'void (VMUINT8 *, VMUINT8 *, VMUINT32, VMUINT32, VMUINT32, VMUINT32, VMUINT32)'),
        0x068: ('VmVideoPicUpturn', 'void (VMUINT8 *, VMUINT8 *, VMUINT32 *, VMUINT32 *)'),
        0x06c: ('VmSetCamSampTime', 'void (VMUINT32)'),
        0x070: ('VmIsVideoPlayerRun', 'VMBOOLEAN ()'),
        0x074: ('VmPlayVideo', 'VMBOOLEAN (VMWCHAR *, void *)'),
        0x078: ('VmRegPlayVideoCb', 'void (playVideoCallBack)'),
        0x07c: ('VmGetMediaFileInfo', 'VMBOOLEAN (VMWCHAR *'),
        0x080: ('VmPlayStreamingVideo', 'VMBOOLEAN (VMUINT16 *, VMUINT16, codec_SeekMode_e, codec_videoStreamingMode_e, codec_mediaFormat_t)'),
        0x084: ('VmStopStreamingVideo', 'VMBOOLEAN ()'),
        0x088: ('VmSetDownloadInterface', 'void ('),
        0x08c: ('VmGetStreamingVideoHandle', 'VMUINT32 ()'),
        0x090: ('VmGetStreamingInfo', 'VMBOOLEAN ('),
        0x094: ('VmStreamingFileChange', 'VMBOOLEAN ('),
    },
}
